main: refactor main package
newrelic/nri-kubernetes pull request #163
Opened 2021-07-20 09:09 UTC by roobre

Split from #160 

- Make argumentList a smarter object
- Wrap most of the main logic in a run function which returns an error
- Make logger global (for main package only)
- Minor improvements to error messages and formatting

2021-07-20 09:26 UTC, invidian commented on src/kubernetes.go
> +				return fmt.Errorf("Error getting KSM discoverer: %v", err)
```suggestion
				return fmt.Errorf("getting KSM discoverer: %v", err)
```

2021-07-20 09:26 UTC, invidian commented on src/kubernetes.go
> +				return fmt.Errorf("Error discovering KSM: %v", err)
```suggestion
				return fmt.Errorf("discovering KSM: %v", err)
```

2021-07-20 09:26 UTC, invidian commented on src/main.go
> +var logger log.Logger
Why can't we pass logger explicitly to `run()`?

2021-07-20 09:26 UTC, invidian commented on src/kubernetes.go
> +		return fmt.Errorf("coudl not find %q in env, which should have been set by Kubernetes", nodeNameEnvVar)
```suggestion
		return fmt.Errorf("could not find %q in env, which should have been set by Kubernetes", nodeNameEnvVar)
```

2021-07-20 11:26 UTC, invidian commented on src/kubernetes.go
> +				return fmt.Errorf("discovering KSM: %w", err)
Perhaps `return fmt.Errorf("discovering distributed KSM: %w", err)`.

2021-07-20 11:29 UTC, invidian commented on src/kubernetes.go
> +			logger.Errorf("control plane component %s discovery failed: %v", component.Name, err)
Should you `continue` here? `componentClient` will most likely be nil, right?

2021-07-20 11:29 UTC, invidian commented on src/kubernetes.go
>  		logger.Errorf("Error during Kubelet auto discovering process: %v", err)
Should we return error here?

2021-07-22 12:35 UTC, invidian commented
@roobre linter is still failing.

2021-07-22 21:55 UTC, invidian requested changes
@roobre I had to unresolve conversations which I marked as resolved when I pushed my code to this PR, which has been reverted. It would be nice to get them addressed.

2021-07-23 13:27 UTC, invidian approved these changes

2021-07-28 09:33 UTC, roobre commented
Rebased 😭

2021-07-28 10:46 UTC, invidian approved these changes
Nice! :tada:

2021-08-25 07:40 UTC, paologallinaharbur commented
@roobre Also this one is becoming stale

2021-09-10 12:29 UTC, roobre commented
Closing as with the new architecture in the roadmap, the `main` package will change drastically anyway.

2021-09-10 12:29 UTC, closed without merging

2021-09-10 12:41 UTC, invidian commented
Shall we remove the branch as well?