Add cronjob to testing resources.
newrelic/nri-kubernetes pull request #608
Opened 2023-01-24 23:23 UTC by htroisi

The Kubernetes team is working on adding new metrics for all Kubernetes workloads, including `cronjob`. As a first step in that process, this PR adds a `cronjob` workload that will be used in the local dev environment. 

### Testing Plan

1. Run local dev environment: `make local-env-start`
2. Observe `cronjob` running every 1 minute
3. Test that [e2e testing](https://github.com/newrelic/nri-kubernetes/blob/main/e2e/README.md) completes successfully

2023-01-25 17:26 UTC, htroisi commented
This PR is failing due to a detected vulnerability with the `golang.org/x/net` library. It looks like this PR should bump the version and fix the issue: https://github.com/newrelic/nri-kubernetes/pull/606

2023-01-26 21:51 UTC, philkuz requested changes

2023-01-26 21:51 UTC, philkuz commented on charts/internal/e2e-resources/README.md
> +![Version: 1.4.0-devel](https://img.shields.io/badge/Version-1.4.0--devel-informational?style=flat-square)
You should update Chart.yaml to match this version as well

2023-01-27 17:57 UTC, svetlanabrennan approved these changes

2023-01-30 21:55 UTC, philkuz approved these changes

2023-01-30 22:05 UTC, nserrino approved these changes

2023-01-30 22:05 UTC, merged